name = "aswin-portfolio"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[[routes]]
pattern = "aswincloud.com/*"
zone_name = "aswincloud.com"

[[routes]]
pattern = "www.aswincloud.com/*"
zone_name = "aswincloud.com"

[assets]
directory = "./build"
binding = "ASSETS"