name = "aswin-portfolio"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[[routes]]
pattern = "aswinlocal.in/*"
zone_name = "aswinlocal.in"

[[routes]]
pattern = "www.aswinlocal.in/*"
zone_name = "aswinlocal.in"

[site]
bucket = "./dist" 